name: Deploy Website

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Surge
        run: npm install -g surge;

      - name: Deploy to Surge
        run: surge ./ ajmal-proj1.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Verify Deployment
        run: |
          if [ "$?" -eq 0 ]; then
            echo "Deployment successful!"
          else
            echo "Deployment failed!"
            exit 1
          fi
